### ISSUE TITLE
Expose the neuroglancer layer interface to enable easy visualization of "external" data

### ISSUE THREAD

**Issue by ch-schiffer** [FZJ-INM1-BDA/siibra-explorer#1188]
It would be great to be able to view arbitrary data in the viewer, similar to how it is possible in vanilla neuroglancer. This would combine the streamlined design of siibra-explorer with the flexibility to view data from different sources (e.g., self-hosted) provided by neuroglancer. This would make the viewer much more valuable as a "general purpose viewer", as it would allow to quickly superimpose data in the provided templates spaces (e.g., BigBrain). 
As this is probably mainly interesting for advanced users, it might be a good idea to hide the related UI elements by default, and introduce some kind of "expert/advanced mode".
In the same spirit, it would be really nice to expose the JSON configuration option (button "{}" on the top right in vanilla neuroglancer) in this expert mode. I frequently use this feature to programmatically configure neuroglancer views, and it would be great to be able to do the same in siibra-explorer.

**Comment by xgui3783** [comment]
The features you are asking for (if I get them right) are:

- allow user volumes to be overlayed with existing template (+ segmentations)
- fine tuning of neuroglancer instance

the former is certainly in scope. I believe drag and drop nifti should already be working. Further, other applications can communicate with siibra-explorer via the [plugin api](https://github.com/FZJ-INM1-BDA/siibra-explorer/tree/master/src/plugin), specifically, the [loadLayers](https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/master/src/plugin/request.md#sxplrloadlayers), [updateLayers](https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/master/src/plugin/request.md#sxplrupdatelayers) and [removeLayers](https://github.com/FZJ-INM1-BDA/siibra-explorer/blob/master/src/plugin/request.md#sxplrremovelayers) calls.

Currently, the plugin API calls only works if the plugin is embedded in the viewer (as an iFrame). In the future, we have plans to make this work if another application embeds the viewer (as an iFrame) . 

Exposing the neuroglancer configuration is simple enough, but it will most likely:

- break the view (somehow) since the siibra-explorer assumes it alone has control over neuroglancer/nehuba 
- not persist the state via URL (we rewrote how state is persisted in the URL)

**Comment by xgui3783** [comment]
completely forgot about this issue. 

there actually has been a mechanism to overlay a single (no more than one) layer for quite some time now.

e..g

```
https://atlases.ebrains.eu/viewer/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:minds:core:parcellationatlas:v1.0.0:94c1125b-b87e-45e4-901c-00daee7f2579-290/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..7eI0..BLbW.1.6Udz~..pq_/x-overlay-layer:precomputed:%2F%2Fhttps:%2F%2Fneuroglancer.humanbrainproject.eu%2Fprecomputed%2FJuBrain%2Fv2.2c%2Fcolin27_seg
```

The above url is generated with https://github.com/xgui3783/siibra-explorer-toolsuite with the following code:

```python
from siibra_explorer_toolsuite import run
import siibra
parcellation = siibra.parcellations["2.9"]
region = parcellation.get_region("hoc1 left")
url = run(siibra.atlases["human"], siibra.spaces["big brain"], parcellation, external_url=f"precomputed://https://neuroglancer.humanbrainproject.eu/precomputed/JuBrain/v2.2c/colin27_seg")
print(url)
```
