### ISSUE TITLE
allow custom neuroglancer shaders to be placed in a shader.json file

### ISSUE THREAD

**Issue by PolarBean** [FZJ-INM1-BDA/siibra-explorer#1336]
Hi, 

apologies for all the requests, siibra is great and I am enjoying using it. Would it be possible in the future to allow the inclusion of a shader.json in the same manner as transform.json is included. This file would include the code you would normally find in the shader input box under the render tab in neuroglancer. 

Thanks in advance!

**Comment by xgui3783** [comment]
This has been talked about with @pacher . 

I would argue that it should be called something more generic like `volume.info.json`.

It can contain the following fields:

- min
- max
- shader
- transform

for now. 

The transform field is duplicated from `transform.json`, but it would be nice to eventually have only one metadata file, rather than two

ping @pacher if you have comments/suggestions

**Comment by xgui3783** [comment]
discussed with @pacher 

likely, we will use a filename called `meta` for metadata

we will produce a json schema and a few examples, then call for an RFC.

**Comment by PolarBean** [comment]
This all seems very reasonable!

**Comment by xgui3783** [comment]
closing this issue for now. 

any further discussion should be had in #1348
