### ISSUE TITLE
Simplify MNI coordinates input option

### ISSUE THREAD

**Issue by KimLothmann** [FZJ-INM1-BDA/siibra-explorer#1402]
It is difficult to insert own MNI coordinates. Sometimes I need two attempts to enter the coordinates. Is it possible to make this easier by maybe making 3 boxes to click in? 

Addition: Afterwards you get the associated area. Is it possible that the information box on the left opens directly to the area? Without clicking on it again? I can imagine that this will be more self-explaining.

Alternatively: When entering the coordinates, the side bar opens and the same happens as with the "right click" - the areas to the coordinate are show up with their probability, since the maps overlap.

**Comment by xgui3783** [comment]
> It is difficult to insert own MNI coordinates. Sometimes I need two attempts to enter the coordinates. Is it possible to make this easier by maybe making 3 boxes to click in?

we will see what can be done

> Addition: Afterwards you get the associated area. Is it possible that the information box on the left opens directly to the area? Without clicking on it again? I can imagine that this will be more self-explaining.

Do you mean the following:

current:

1/ user enters MNI 152 coord in text box
2/ viewer navigates to the coordinate
3/ user left click the center of the view port to select the ROI

desired/expected:

1/ user enters the MNI 152 coord in text box
2/ viewer navigates to the coordinate AND if overlaps with a region, selects the region

?

> Alternatively: When entering the coordinates, the side bar opens and the same happens as with the "right click" - the areas to the coordinate are show up with their probability, since the maps overlap.

This is an interesting suggestion and usecase. Since we developed the two features separately, they do not interact in any way at the moment. But, IMO, it's only natural to see some interactions between these two components.

**Comment by KimLothmann** [comment]
I made you an example, to show you what could help
![image](https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/131377539/206ba123-bc44-4956-b405-6f3e7a86b5f3)

**Comment by xgui3783** [comment]
since v2.14.0, the proposed change has been implemented (see screenshot)

![image](https://github.com/FZJ-INM1-BDA/siibra-explorer/assets/19381783/b84640fe-f901-4235-bacb-7dbbae8df69f)
