### ISSUE TITLE
Default parcellation template for mouse and rat atlas

### ISSUE THREAD

**Issue by Majpuc** [FZJ-INM1-BDA/siibra-explorer#777]
Would it be possible to put in default the parcellation template having the highest number of datasets coupled to the atlas?

**Comment by xgui3783** [comment]
@Majpuc we have reworked how datasets are retrieved (no longer based on region names, but `@id` of the regions, as per registered in the KG)

For example https://interactive-viewer-next.apps-dev.hbp.eu/?templateSelected=Waxholm+Space+rat+brain+MRI%2FDTI&parcellationSelected=Waxholm+Space+rat+brain+atlas+v3&cRegionsSelected=%7B%22v3%22%3A%221S%22%7D&cNavigation=0.0.0.-W000..2-8Bnd.2_tvb9._yymE._tYzz..1Sjt..22%7E.Lqll%7E.33ix..Eas

49 datasets associated with neocortex in v3 of waxholm

or https://interactive-viewer-next.apps-dev.hbp.eu/?templateSelected=Allen+Mouse+Common+Coordinate+Framework+v3&parcellationSelected=Allen+Mouse+Common+Coordinate+Framework+v3+2015&cRegionsSelected=%7B%22atlas%22%3A%225w%22%7D&cNavigation=0.0.0.-W000.._XxAw.-GC6L.2-2QPq.2_Ylx_..cwd..Uzz.O43%7E.HD0%7E..7JP

20 datastes associated with Supplemental somatosensory area of allen ccf v3 2015

Currently, when an atlas is selected, the "newest" parcellation will be selected. But we can change that behaviour if unsuitable.

**Comment by xgui3783** [comment]
PS, the links above point to dev version of the atlas viewer, and not suitable for wide distribution. 

We are aiming to release this once we finish up on some features.

**Comment by Majpuc** [comment]
I don't really understand how this will look like for the user... Around 50 datasets are linked CCFv3_2015 and 50 datasets linked to CCFv3_2017. What about the regions that differ between these two parcellation? In your regionlist do you collapse all brain regions from both parcellations?

**Comment by xgui3783** [comment]
Are you referring to the production version of the interactive atlas viewer at https://interactive-viewer.apps.hbp.eu/ ?

if that is the case, the method used to retrieve the datasets are flawed, and prone to error. If you are interested, here is a link describing how the dataset retrieval is done: <https://interactive-viewer.readthedocs.io/en/latest/advanced/datasets/>

In short, it first filter the dataset by species, then check if any of the parcellation region **name** matches to that is linked in KG.

(indeed, it will not be able to distinguish neocortex waxholm v2 against neocortex waxholm v3, which is an issue for us)

Because it is so error prone, we have changed the way it behaves in the upcoming version of the viewer <https://interactive-viewer-next.apps-dev.hbp.eu/> . if you are interested, doc is <https://interactive-viewer-next.apps-dev.hbp.eu/docs/advanced/datasets/>

In the new version, datasets will only be shown when a parcellation region is selected. Datasets are now fetched according to its `@id` as registered in KG, rather than its name. 

IAV gets the `@id`, currently hardcoded (allen mouse ccf3 2015 , 2017: <https://github.com/HumanBrainProject/interactive-viewer/blob/dev/src/res/ext/allenMouse.json>, waxholm v1.01, v2, v3 <https://github.com/HumanBrainProject/interactive-viewer/blob/dev/src/res/ext/waxholmRatV2_0.json>), search for the key `relatedAreas` or `fullId` 

We foresee that this hardcoded id's will be replaced by SANDS in the coming ... months, if not weeks.

**Comment by Majpuc** [comment]
Also, as I mentioned earlier, we are missing the template v2 of WHS. Would you be able to add it? https://github.com/HumanBrainProject/interactive-viewer/issues/657

**Comment by Majpuc** [comment]
Sorry, the messages are not updated in the correct order... Thanks! I will have a look at the new version. When do you expect to release it?

**Comment by xgui3783** [comment]
>  Is there a was of telling the user that he or she might find more datasets with another parcellation version?

In the upcoming version (not using SANDS), I would imagine, we can add the parcellation region in `relatedAreas` property. 

SANDS will already have `otherAnatomicalRelation`,  <https://github.com/HumanBrainProject/openMINDS_SANDS/blob/e174e567600aa13fa81bc9c8f6bc1d7f9e7624c5/schemas/anatomicalEntity.schema.tpl.json#L22-L30> which, I imagine, can be used to retrieve related datasets.

**Comment by xgui3783** [comment]
> Also, as I mentioned earlier, we are missing the template v2 of WHS. Would you be able to add it? #657

do you mean v2 of CCF?

AFAIK, v2 of waxholm was amongst the very first atlases integrated.

**Comment by Majpuc** [comment]
Ok, I see it now. I think there is lagging depending on the internet connection. Some parts are missing when it is loading slowly...

**Comment by Majpuc** [comment]
> 
> 
> > Also, as I mentioned earlier, we are missing the template v2 of WHS. Would you be able to add it? #657
> 
> do you mean v2 of CCF?
> 
> AFAIK, v2 of waxholm was amongst the very first atlases integrated.

Yes, V2 of the Mouse atlas, sorry for the confusion!

**Comment by xgui3783** [comment]
> Yes, V2 of the Mouse atlas, sorry for the confusion!

We have that on the todo, but unfortunately, we have some competing deadlines. 

In the near future, we will be able to separate the data side from the UI side, in a much more clear fashion (ideally, we should also be able to publish a how-to), so that integrating new atlases should happen on a clearer manner.

**Comment by xgui3783** [comment]
PS, please take a look at the new version and report any problems here?

If no issues found, please also let us know (in this thread), then close the issue?

**Comment by Majpuc** [comment]
I like that the Atlas name is shown in the left lower corner and think the parcellations should be visible per default when you start in order for the user to become aware of these different parcellations. Then, they could appear and disappear when you click on the name as it is doing now.

**Comment by Majpuc** [comment]
I might have to test this on my stationary PC at the lab because from home, on my laptop, I feel there is a lot of lagging and that some features seem not to work but in fact are working fine. I will let you know.

**Comment by xgui3783** [comment]
> I might have to test this on my stationary PC at the lab because from home, on my laptop, I feel there is a lot of lagging and that some features seem not to work but in fact are working fine. I will let you know.

Is it significantly slower than the current version? https://interactive-viewer.apps.hbp.eu/ if that is indeed the case, we will have to dedicate some resource to take a look at what is the issue.

**Comment by Majpuc** [comment]
No, on my laptop now , it is approximately the same.

**Comment by xgui3783** [comment]
Then it is likely due the large number of meshes, especially in allen ccf v3. 

In the future, hopefully, we can be a bit clever when it comes to loading only the minimum number of mesh (tracked at https://github.com/HumanBrainProject/interactive-viewer/issues/781)

Coming back to the issue at hand, if you find abberation with regard to datasets fetched in the dev version, please report them here. 

if everything seems in order, please also let us know in this thread, and close the issue.

**Comment by Majpuc** [comment]
I have tested the dev version on my stationary PC with fast internet connection. it is working much better and is very nice. I still have some issues with some brain regions meshes not showing up in the different windows when selecting them, but I guess you're still working on this... Let me know if you'd like more feedback or maybe later.

**Comment by xgui3783** [comment]
>  I still have some issues with some brain regions meshes not showing up in the different windows when selecting them

This would be an issue of concern. Can you be a bit more specific on which mesh? (if you find an issue, copy/paste the URL and screenshot would help us diagnose the issue very much)

**Comment by Majpuc** [comment]
@xgui3783 I think you can close this issue. Thanks
