### ISSUE TITLE
[Bug] Parcellation regions does not look correct on android device

### ISSUE THREAD

**Issue by fsdavid** [FZJ-INM1-BDA/siibra-explorer#843]
to reproduce:

1/ go to human multilevel with android device

actual behaviour:
![image](https://user-images.githubusercontent.com/26521731/104937285-def8e580-59ad-11eb-904e-ecc28d98ead1.png)

**Comment by xgui3783** [comment]
cannot seem to reproduce. was it a result of internet connection?

**Comment by fsdavid** [comment]
> cannot seem to reproduce. was it a result of internet connection?

No, it was not. There is still the same bug on:

Google Pixel 3 
Chrome version 88.0.4324.141
Edge - version 45.12.4.5137
Firefox - 85.1.1

**Comment by xgui3783** [comment]
yup, I can reproduce. on browser stack at least. But I don't know how/if the issue is on the interactive atlas viewer side. It's probably on the neuroglancer viewer (at least with the current fork).

with the concerned device, [check link](https://interactive-viewer-next.apps-dev.hbp.eu/vanilla.html#!%7B%22layers%22:%5B%7B%22transform%22:%5B%5B1%2C0%2C0%2C-96500000%5D%2C%5B0%2C1%2C0%2C-132500000%5D%2C%5B0%2C0%2C1%2C-78500000%5D%2C%5B0%2C0%2C0%2C1%5D%5D%2C%22source%22:%22precomputed://https://neuroglancer.humanbrainproject.org/precomputed/Fiber_Bundle/mni_icbm152_t1_tal_nlin_asym_09c_masked%22%2C%22type%22:%22image%22%2C%22name%22:%22mni152%22%7D%2C%7B%22transform%22:%5B%5B1%2C0%2C0%2C-96500000%5D%2C%5B0%2C1%2C0%2C-132500000%5D%2C%5B0%2C0%2C1%2C-78500000%5D%2C%5B0%2C0%2C0%2C1%5D%5D%2C%22source%22:%22precomputed://https://neuroglancer.humanbrainproject.eu/precomputed/data-repo/20201204_JulichBrainV3_0_hemisphereSplit/precomputed/JuBrain_Map_icbm_v30_r%22%2C%22type%22:%22segmentation%22%2C%22name%22:%22MNI152_V25_RIGHT_NG_SPLIT_HEMISPHERE%22%7D%2C%7B%22transform%22:%5B%5B1%2C0%2C0%2C-96500000%5D%2C%5B0%2C1%2C0%2C-132500000%5D%2C%5B0%2C0%2C1%2C-78500000%5D%2C%5B0%2C0%2C0%2C1%5D%5D%2C%22source%22:%22precomputed://https://neuroglancer.humanbrainproject.eu/precomputed/data-repo/20201204_JulichBrainV3_0_hemisphereSplit/precomputed/JuBrain_Map_icbm_v30_l%22%2C%22type%22:%22segmentation%22%2C%22name%22:%22MNI152_V25_LEFT_NG_SPLIT_HEMISPHERE%22%7D%5D%2C%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B1000000%2C1000000%2C1000000%5D%2C%22voxelCoordinates%22:%5B0%2C-32%2C0%5D%7D%7D%2C%22zoomFactor%22:450000%7D%2C%22showDefaultAnnotations%22:false%2C%22perspectiveOrientation%22:%5B-0.2753947079181671%2C0.6631333827972412%2C-0.6360703706741333%2C0.2825356423854828%5D%2C%22perspectiveZoom%22:3000000%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%224panel%22%7D) 

I want to check with the upstream neuroglancer, and see if the issue persist

**Comment by fsdavid** [comment]
The bug exists on Neuromancer too. So this is definitely the Neuromancer side.

**Comment by xgui3783** [comment]
Likely device resource constrain. If issue persist, feel free to reopen
